//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoWebBanda.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cancion", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Cancion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int idCancionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DuracionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GeneroField;
        
        private int idAlbumField;
        
        private int idPlataformaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int idCancion {
            get {
                return this.idCancionField;
            }
            set {
                if ((this.idCancionField.Equals(value) != true)) {
                    this.idCancionField = value;
                    this.RaisePropertyChanged("idCancion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Duracion {
            get {
                return this.DuracionField;
            }
            set {
                if ((object.ReferenceEquals(this.DuracionField, value) != true)) {
                    this.DuracionField = value;
                    this.RaisePropertyChanged("Duracion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Genero {
            get {
                return this.GeneroField;
            }
            set {
                if ((object.ReferenceEquals(this.GeneroField, value) != true)) {
                    this.GeneroField = value;
                    this.RaisePropertyChanged("Genero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int idAlbum {
            get {
                return this.idAlbumField;
            }
            set {
                if ((this.idAlbumField.Equals(value) != true)) {
                    this.idAlbumField = value;
                    this.RaisePropertyChanged("idAlbum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int idPlataforma {
            get {
                return this.idPlataformaField;
            }
            set {
                if ((this.idPlataformaField.Equals(value) != true)) {
                    this.idPlataformaField = value;
                    this.RaisePropertyChanged("idPlataforma");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ServiceDBSoap")]
    public interface ServiceDBSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        ProyectoWebBanda.ServiceReference1.HelloWorldResponse HelloWorld(ProyectoWebBanda.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<ProyectoWebBanda.ServiceReference1.HelloWorldResponse> HelloWorldAsync(ProyectoWebBanda.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ObtenerCancionesResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerCanciones", ReplyAction="*")]
        ProyectoWebBanda.ServiceReference1.ObtenerCancionesResponse ObtenerCanciones(ProyectoWebBanda.ServiceReference1.ObtenerCancionesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerCanciones", ReplyAction="*")]
        System.Threading.Tasks.Task<ProyectoWebBanda.ServiceReference1.ObtenerCancionesResponse> ObtenerCancionesAsync(ProyectoWebBanda.ServiceReference1.ObtenerCancionesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public ProyectoWebBanda.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(ProyectoWebBanda.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProyectoWebBanda.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(ProyectoWebBanda.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ProyectoWebBanda.ServiceReference1.Cancion[] HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(ProyectoWebBanda.ServiceReference1.Cancion[] HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerCancionesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerCanciones", Namespace="http://tempuri.org/", Order=0)]
        public ProyectoWebBanda.ServiceReference1.ObtenerCancionesRequestBody Body;
        
        public ObtenerCancionesRequest() {
        }
        
        public ObtenerCancionesRequest(ProyectoWebBanda.ServiceReference1.ObtenerCancionesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ObtenerCancionesRequestBody {
        
        public ObtenerCancionesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerCancionesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerCancionesResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProyectoWebBanda.ServiceReference1.ObtenerCancionesResponseBody Body;
        
        public ObtenerCancionesResponse() {
        }
        
        public ObtenerCancionesResponse(ProyectoWebBanda.ServiceReference1.ObtenerCancionesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerCancionesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ProyectoWebBanda.ServiceReference1.Cancion[] ObtenerCancionesResult;
        
        public ObtenerCancionesResponseBody() {
        }
        
        public ObtenerCancionesResponseBody(ProyectoWebBanda.ServiceReference1.Cancion[] ObtenerCancionesResult) {
            this.ObtenerCancionesResult = ObtenerCancionesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceDBSoapChannel : ProyectoWebBanda.ServiceReference1.ServiceDBSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceDBSoapClient : System.ServiceModel.ClientBase<ProyectoWebBanda.ServiceReference1.ServiceDBSoap>, ProyectoWebBanda.ServiceReference1.ServiceDBSoap {
        
        public ServiceDBSoapClient() {
        }
        
        public ServiceDBSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceDBSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDBSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDBSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoWebBanda.ServiceReference1.HelloWorldResponse ProyectoWebBanda.ServiceReference1.ServiceDBSoap.HelloWorld(ProyectoWebBanda.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public ProyectoWebBanda.ServiceReference1.Cancion[] HelloWorld() {
            ProyectoWebBanda.ServiceReference1.HelloWorldRequest inValue = new ProyectoWebBanda.ServiceReference1.HelloWorldRequest();
            inValue.Body = new ProyectoWebBanda.ServiceReference1.HelloWorldRequestBody();
            ProyectoWebBanda.ServiceReference1.HelloWorldResponse retVal = ((ProyectoWebBanda.ServiceReference1.ServiceDBSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoWebBanda.ServiceReference1.HelloWorldResponse> ProyectoWebBanda.ServiceReference1.ServiceDBSoap.HelloWorldAsync(ProyectoWebBanda.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoWebBanda.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            ProyectoWebBanda.ServiceReference1.HelloWorldRequest inValue = new ProyectoWebBanda.ServiceReference1.HelloWorldRequest();
            inValue.Body = new ProyectoWebBanda.ServiceReference1.HelloWorldRequestBody();
            return ((ProyectoWebBanda.ServiceReference1.ServiceDBSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoWebBanda.ServiceReference1.ObtenerCancionesResponse ProyectoWebBanda.ServiceReference1.ServiceDBSoap.ObtenerCanciones(ProyectoWebBanda.ServiceReference1.ObtenerCancionesRequest request) {
            return base.Channel.ObtenerCanciones(request);
        }
        
        public ProyectoWebBanda.ServiceReference1.Cancion[] ObtenerCanciones() {
            ProyectoWebBanda.ServiceReference1.ObtenerCancionesRequest inValue = new ProyectoWebBanda.ServiceReference1.ObtenerCancionesRequest();
            inValue.Body = new ProyectoWebBanda.ServiceReference1.ObtenerCancionesRequestBody();
            ProyectoWebBanda.ServiceReference1.ObtenerCancionesResponse retVal = ((ProyectoWebBanda.ServiceReference1.ServiceDBSoap)(this)).ObtenerCanciones(inValue);
            return retVal.Body.ObtenerCancionesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoWebBanda.ServiceReference1.ObtenerCancionesResponse> ProyectoWebBanda.ServiceReference1.ServiceDBSoap.ObtenerCancionesAsync(ProyectoWebBanda.ServiceReference1.ObtenerCancionesRequest request) {
            return base.Channel.ObtenerCancionesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoWebBanda.ServiceReference1.ObtenerCancionesResponse> ObtenerCancionesAsync() {
            ProyectoWebBanda.ServiceReference1.ObtenerCancionesRequest inValue = new ProyectoWebBanda.ServiceReference1.ObtenerCancionesRequest();
            inValue.Body = new ProyectoWebBanda.ServiceReference1.ObtenerCancionesRequestBody();
            return ((ProyectoWebBanda.ServiceReference1.ServiceDBSoap)(this)).ObtenerCancionesAsync(inValue);
        }
    }
}
